version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=goFund
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
